use super::skill::{Skill, SkillUpdateInput};
use serde::{Deserialize, Serialize};

/// Skills Struct
#[derive(Serialize, Deserialize, Debug)]
pub struct Skills {
    pub academics: Skill,
    pub athletics: Skill,
    pub animal_ken: Skill,
    pub awareness: Skill,
    pub brawl: Skill,
    pub computer: Skill,
    pub craft_a: Skill,
    pub craft_b: Skill,
    pub dodge: Skill,
    pub drive: Skill,
    pub empathy: Skill,
    pub firearms: Skill,
    pub intimidation: Skill,
    pub investigation: Skill,
    pub leadership: Skill,
    pub linguistics: Skill,
    pub lore: Skill,
    pub medicine: Skill,
    pub melee: Skill,
    pub occult: Skill,
    pub performance_a: Skill,
    pub performance_b: Skill,
    pub security: Skill,
    pub science_a: Skill,
    pub science_b: Skill,
    pub stealth: Skill,
    pub streetwise: Skill,
    pub subterfuge: Skill,
    pub survival: Skill,
}

/// Struct for Updating the list of skills
#[derive(Serialize, Deserialize, Debug)]
pub struct SkillsUpdateInput {
    pub academics: Option<SkillUpdateInput>,
    pub athletics: Option<SkillUpdateInput>,
    pub animal_ken: Option<SkillUpdateInput>,
    pub awareness: Option<SkillUpdateInput>,
    pub brawl: Option<SkillUpdateInput>,
    pub computer: Option<SkillUpdateInput>,
    pub craft_a: Option<SkillUpdateInput>,
    pub craft_b: Option<SkillUpdateInput>,
    pub dodge: Option<SkillUpdateInput>,
    pub drive: Option<SkillUpdateInput>,
    pub empathy: Option<SkillUpdateInput>,
    pub firearms: Option<SkillUpdateInput>,
    pub intimidation: Option<SkillUpdateInput>,
    pub investigation: Option<SkillUpdateInput>,
    pub leadership: Option<SkillUpdateInput>,
    pub linguistics: Option<SkillUpdateInput>,
    pub lore: Option<SkillUpdateInput>,
    pub medicine: Option<SkillUpdateInput>,
    pub melee: Option<SkillUpdateInput>,
    pub occult: Option<SkillUpdateInput>,
    pub performance_a: Option<SkillUpdateInput>,
    pub performance_b: Option<SkillUpdateInput>,
    pub security: Option<SkillUpdateInput>,
    pub science_a: Option<SkillUpdateInput>,
    pub science_b: Option<SkillUpdateInput>,
    pub stealth: Option<SkillUpdateInput>,
    pub streetwise: Option<SkillUpdateInput>,
    pub subterfuge: Option<SkillUpdateInput>,
    pub survival: Option<SkillUpdateInput>,
}
